version: '2'
volumes:
    resin-data:
    dashboard-data:
    database:
      
services:
  node-red:
    build: ./node-red
    volumes:
      - 'resin-data:/data'
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
    environment:
      - "USERNAME=balena"
      - "PASSWORD=balena"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - 80:80

  mqtt:
    image: arm32v6/eclipse-mosquitto
    network_mode: host
    ports:
      - "1883:1883"
    restart: always

  connector:
    image: balenablocks/connector
    network_mode: host
    restart: always
    labels:
      io.balena.features.balena-api: '1' 
      io.balena.features.supervisor-api: '1'
    privileged: true 
  
  dashboard:
    image: balenablocks/dashboard
    restart: always
    volumes:
      - "dashboard-data:/dashboard-data"
    ports:
      - "8080"

  influxdb:
    image: influxdb@sha256:b4529fd53e9022bd1e83aaf04c6c6a1ebfffdfa112c31367d69da1354983a24b
    container_name: influxdb
    restart: always
    volumes:
      - 'database:/var/lib/influxdb'
  
